services:

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    container_name: nginx-proxy-wachat
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_SOCKET_UNIX}:/tmp/docker.sock:ro
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhostd:/etc/nginx/vhost.d:rw
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - ./nginx-proxy/custom.conf:/etc/nginx/conf.d/custom.conf:rw
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    container_name: letsencrypt-wachat
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/vhostd:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
      - ./nginx-proxy/acme:/etc/acme.sh
      - ${DOCKER_SOCKET_UNIX}:/var/run/docker.sock:ro

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: postgres-wachat
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ./postgresData:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant-wachat
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: redis-wachat
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redisData:/data
    environment:
      - VIRTUAL_HOST=redis.1bit.ar
      - VIRTUAL_PORT=6379

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    hostname: n8n
    container_name: n8n-wachat
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      #aca hay que poner el puerto es para que conecte el webhook de WA
      - WEBHOOK_URL=https://${DOMAIN_NAME}:443/
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_PORT=5678
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./n8nData:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    container_name: evolution-api-wachat
    hostname: evolution
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/evolution?schema=public
      - AUTHENTICATION_API_KEY=${ENCRYPTION_KEY}
      - VIRTUAL_HOST=evolutionapi.1bit.ar
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=evolutionapi.1bit.ar
      - SERVER_URL=https://evolutionapi.1bit.ar
      - CACHE_REDIS_ENABLED=false
      - INSTANCE_RECONNECT=true
      - DATABASE_SAVE_DATA_INSTANCE=true
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1034126560
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NODE_ENV=production
      - CORS_ENABLED=true
      - CORS_ORIGIN=*
      - AUTHENTICATION_EXPOSE_IN_FETCH_QR=true
      - LOG_LEVEL=info
      - LOG_BAILEYS=error
      - CHATWOOT_ENABLED=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - CHATWOOT_URL=http://chatwoot-web:3000
    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

  chatwoot-base:
    # image: chatwoot/chatwoot:latest
    &chatwoot-base
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./chatwootData:/app/storage

  chatwoot-web:
    <<: *chatwoot-base
    container_name: chatwoot-web-wachat
    command: >
      sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - VIRTUAL_HOST=${CHATWOOT_DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${CHATWOOT_DOMAIN}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - RAILS_ENV=production
      - FORCE_SSL_ONLY=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  chatwoot-worker:
    <<: *chatwoot-base
    container_name: chatwoot-worker-wachat
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
