#!/bin/bash
set -e;


if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
		CREATE DATABASE evolution;
		CREATE DATABASE chat_app;
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
		GRANT ALL PRIVILEGES ON DATABASE evolution TO "${POSTGRES_NON_ROOT_USER}";
		GRANT ALL PRIVILEGES ON DATABASE chat_app TO "${POSTGRES_NON_ROOT_USER}";
		GRANT CREATE ON SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
	EOSQL
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "evolution" <<-EOSQL
		GRANT ALL ON SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
	EOSQL
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "chat_app" <<-EOSQL
		GRANT ALL ON SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi